services:
  postgres:
    image: postgres:16
    env_file:
      - ./dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./packages:/app/packages
      - ./run.py:/app/run.py
    env_file:
      - ./dev.env
    depends_on:
      - postgres

volumes:
  postgres_data:
