"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-12 04:14:29.040319

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "microscopes",
        sa.Column("microscope_id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("microscope_type", sa.String(), server_default=sa.text("'TEM'"), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("microscope_id", name=op.f("pk_microscopes")),
        sa.UniqueConstraint("label", name=op.f("uq_microscopes_label")),
    )
    op.create_table(
        "specimens",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("specimen_images", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("functional_imaging_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specimens")),
    )
    op.create_index(op.f("ix_specimens_specimen_id"), "specimens", ["specimen_id"], unique=True)
    op.create_table(
        "substrates",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("media_id", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("refpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("refpoint_world", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("apertures", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_substrates")),
    )
    op.create_index(op.f("ix_substrates_media_id"), "substrates", ["media_id"], unique=True)
    op.create_index("ix_substrates_media_type_status", "substrates", ["media_type", "status"], unique=False)
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("block_id", sa.String(), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=False),
        sa.Column("microCT_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["specimen_id"], ["specimens.specimen_id"], name=op.f("fk_blocks_specimen_id_specimens")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
        sa.UniqueConstraint("specimen_id", "block_id", name="uq_blocks_specimen_block"),
    )
    op.create_table(
        "datasets",
        sa.Column("dataset_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("specimen_id", sa.String(), nullable=True),
        sa.Column("parent_dataset_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("size_class", sa.String(), nullable=False),
        sa.Column("tile_hash_modulus", sa.Integer(), nullable=True),
        sa.Column("estimated_tile_count", sa.BigInteger(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('collecting', 'collected', 'archived')", name=op.f("ck_datasets_status_vocab")),
        sa.ForeignKeyConstraint(
            ["parent_dataset_id"], ["datasets.dataset_id"], name=op.f("fk_datasets_parent_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["specimen_id"], ["specimens.specimen_id"], name=op.f("fk_datasets_specimen_id_specimens")
        ),
        sa.PrimaryKeyConstraint("dataset_id", name=op.f("pk_datasets")),
    )
    op.create_index(op.f("ix_datasets_name"), "datasets", ["name"], unique=True)
    op.create_table(
        "lens_corrections",
        sa.Column("lc_id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("microscope_id", sa.UUID(), nullable=False),
        sa.Column("magnification", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_run_id", sa.UUID(), nullable=True),
        sa.Column("source_dataset_id", sa.UUID(), nullable=True),
        sa.Column("shared_transform", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correction_x_uri", sa.String(), nullable=True),
        sa.Column("correction_y_uri", sa.String(), nullable=True),
        sa.Column("solver_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["microscope_id"], ["microscopes.microscope_id"], name=op.f("fk_lens_corrections_microscope_id_microscopes")
        ),
        sa.PrimaryKeyConstraint("lc_id", name=op.f("pk_lens_corrections")),
    )
    op.create_index(
        "ix_lens_corrections_microscope_mag",
        "lens_corrections",
        ["microscope_id", "magnification", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "cutting_sessions",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("cutting_session_id", sa.String(), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=False),
        sa.Column("block_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("sectioning_device", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("knife_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["specimen_id", "block_id"],
            ["blocks.specimen_id", "blocks.block_id"],
            name=op.f("fk_cutting_sessions_specimen_id_blocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cutting_sessions")),
    )
    op.create_index(
        op.f("ix_cutting_sessions_cutting_session_id"), "cutting_sessions", ["cutting_session_id"], unique=True
    )
    op.create_index(op.f("ix_cutting_sessions_operator"), "cutting_sessions", ["operator"], unique=False)
    op.create_index("ix_cutting_sessions_specimen_block", "cutting_sessions", ["specimen_id", "block_id"], unique=False)
    op.create_table(
        "tiles",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("raster_index", sa.Integer(), nullable=False),
        sa.Column("tile_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("stage_x_nm", sa.Double(), nullable=False),
        sa.Column("stage_y_nm", sa.Double(), nullable=False),
        sa.Column("montage_row", sa.Integer(), nullable=False),
        sa.Column("montage_col", sa.Integer(), nullable=False),
        sa.Column("focus_score", sa.REAL(), nullable=True),
        sa.Column("min_value", sa.REAL(), nullable=True),
        sa.Column("max_value", sa.REAL(), nullable=True),
        sa.Column("mean_value", sa.REAL(), nullable=True),
        sa.Column("std_value", sa.REAL(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=False),
        sa.Column("matcher", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("supertile_id", sa.String(), nullable=True),
        sa.Column("supertile_raster_position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.dataset_id"], name=op.f("fk_tiles_dataset_id_datasets")),
        sa.PrimaryKeyConstraint("dataset_id", "run_id", "raster_index", name=op.f("pk_tiles")),
        postgresql_partition_by="LIST (dataset_id)",
    )
    op.create_index(
        "ix_tiles_focus_score_nn",
        "tiles",
        ["dataset_id", "focus_score"],
        unique=False,
        postgresql_where=sa.text("focus_score IS NOT NULL"),
    )
    op.create_index(
        "ix_tiles_supertile_id_nn",
        "tiles",
        ["supertile_id"],
        unique=False,
        postgresql_where=sa.text("supertile_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_tiles_tile_id"), "tiles", ["tile_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("section_id", sa.String(), nullable=False),
        sa.Column("section_number", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cutting_session_id", sa.String(), nullable=False),
        sa.Column("block_id", sa.String(), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=False),
        sa.Column("media_id", sa.String(), nullable=False),
        sa.Column("optical_image", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("aperture_uid", sa.String(), nullable=True),
        sa.Column("aperture_index", sa.Integer(), nullable=True),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("condition", sa.String(), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("condition_reason", sa.String(), nullable=True),
        sa.Column("section_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "condition IN ('ok', 'damaged', 'destroyed', 'contaminated', 'lost')",
            name=op.f("ck_sections_condition_vocab"),
        ),
        sa.ForeignKeyConstraint(
            ["cutting_session_id"],
            ["cutting_sessions.cutting_session_id"],
            name=op.f("fk_sections_cutting_session_id_cutting_sessions"),
        ),
        sa.ForeignKeyConstraint(["media_id"], ["substrates.media_id"], name=op.f("fk_sections_media_id_substrates")),
        sa.ForeignKeyConstraint(
            ["specimen_id", "block_id"],
            ["blocks.specimen_id", "blocks.block_id"],
            name=op.f("fk_sections_specimen_id_blocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("cutting_session_id", "section_number", name="uq_sections_session_number"),
    )
    op.create_index(
        "ix_sections_barcode_nn", "sections", ["barcode"], unique=False, postgresql_where=sa.text("barcode IS NOT NULL")
    )
    op.create_index(op.f("ix_sections_media_id"), "sections", ["media_id"], unique=False)
    op.create_index(op.f("ix_sections_section_id"), "sections", ["section_id"], unique=True)
    op.create_index("ix_sections_specimen_block", "sections", ["specimen_id", "block_id"], unique=False)
    op.create_table(
        "rois",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("roi_id", sa.String(), nullable=False),
        sa.Column("roi_number", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.String(), nullable=False),
        sa.Column("block_id", sa.String(), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=False),
        sa.Column("substrate_media_id", sa.String(), nullable=False),
        sa.Column("hierarchy_level", sa.Integer(), nullable=False),
        sa.Column("parent_roi_id", sa.String(), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("section_number", sa.Integer(), nullable=True),
        sa.Column("roi_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.dataset_id"], name=op.f("fk_rois_dataset_id_datasets")),
        sa.ForeignKeyConstraint(["parent_roi_id"], ["rois.roi_id"], name=op.f("fk_rois_parent_roi_id_rois")),
        sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], name=op.f("fk_rois_section_id_sections")),
        sa.ForeignKeyConstraint(
            ["specimen_id", "block_id"],
            ["blocks.specimen_id", "blocks.block_id"],
            name=op.f("fk_rois_specimen_id_blocks"),
        ),
        sa.ForeignKeyConstraint(
            ["substrate_media_id"], ["substrates.media_id"], name=op.f("fk_rois_substrate_media_id_substrates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rois")),
        sa.UniqueConstraint("roi_id", name=op.f("uq_rois_roi_id")),
    )
    op.create_index(
        "ix_rois_dataset_id_nn",
        "rois",
        ["dataset_id"],
        unique=False,
        postgresql_where=sa.text("dataset_id IS NOT NULL"),
    )
    op.create_index(
        "ix_rois_parent_roi_id_nn",
        "rois",
        ["parent_roi_id"],
        unique=False,
        postgresql_where=sa.text("parent_roi_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_rois_section_id"), "rois", ["section_id"], unique=False)
    op.create_index("ix_rois_specimen_block", "rois", ["specimen_id", "block_id"], unique=False)
    op.create_index(op.f("ix_rois_substrate_media_id"), "rois", ["substrate_media_id"], unique=False)
    op.create_table(
        "acquisition_tasks",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=True),
        sa.Column("block_id", sa.String(), nullable=True),
        sa.Column("roi_id", sa.String(), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(), server_default=sa.text("'montage'"), nullable=False),
        sa.Column("superseded_by", sa.String(), nullable=True),
        sa.Column("task_group_id", sa.UUID(), nullable=True),
        sa.Column("tilt_angle_deg", sa.Double(), nullable=True),
        sa.Column("sub_region", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind = 'lens_correction' OR (roi_id IS NOT NULL AND specimen_id IS NOT NULL AND block_id IS NOT NULL)",
            name=op.f("ck_acquisition_tasks_lineage_required_for_montage"),
        ),
        sa.CheckConstraint("kind IN ('montage', 'lens_correction')", name=op.f("ck_acquisition_tasks_kind_vocab")),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.dataset_id"], name=op.f("fk_acquisition_tasks_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(["roi_id"], ["rois.roi_id"], name=op.f("fk_acquisition_tasks_roi_id_rois")),
        sa.ForeignKeyConstraint(
            ["specimen_id", "block_id"],
            ["blocks.specimen_id", "blocks.block_id"],
            name=op.f("fk_acquisition_tasks_specimen_id_blocks"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["acquisition_tasks.task_id"],
            name=op.f("fk_acquisition_tasks_superseded_by_acquisition_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_tasks")),
        sa.UniqueConstraint("task_id", name=op.f("uq_acquisition_tasks_task_id")),
    )
    op.create_index(
        "ix_acquisition_tasks_dataset_id_nn",
        "acquisition_tasks",
        ["dataset_id"],
        unique=False,
        postgresql_where=sa.text("dataset_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_acquisition_tasks_roi_id"), "acquisition_tasks", ["roi_id"], unique=False)
    op.create_index(
        "ix_acquisition_tasks_specimen_block", "acquisition_tasks", ["specimen_id", "block_id"], unique=False
    )
    op.create_index(
        "ix_acquisition_tasks_superseded_nn",
        "acquisition_tasks",
        ["superseded_by"],
        unique=False,
        postgresql_where=sa.text("superseded_by IS NOT NULL"),
    )
    op.create_index(
        "ix_acquisition_tasks_task_group_nn",
        "acquisition_tasks",
        ["task_group_id"],
        unique=False,
        postgresql_where=sa.text("task_group_id IS NOT NULL"),
    )
    op.create_table(
        "acquisitions",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("acquisition_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("montage_id", sa.String(), nullable=False),
        sa.Column("specimen_id", sa.String(), nullable=True),
        sa.Column("roi_id", sa.String(), nullable=True),
        sa.Column("acquisition_task_id", sa.String(), nullable=False),
        sa.Column("microscope_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(), server_default=sa.text("'montage'"), nullable=False),
        sa.Column("lc_id", sa.UUID(), nullable=True),
        sa.Column("hardware_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acquisition_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calibration_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("qc_state", sa.String(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("qc_state_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("qc_state_updated_by", sa.String(), nullable=True),
        sa.Column("transfer_state", sa.String(), server_default=sa.text("'not_started'"), nullable=False),
        sa.Column("transfer_state_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transfer_state_updated_by", sa.String(), nullable=True),
        sa.Column("tile_count", sa.Integer(), nullable=True),
        sa.Column("avg_focus_score", sa.REAL(), nullable=True),
        sa.Column("failed_tile_count", sa.Integer(), nullable=True),
        sa.Column("median_match_quality", sa.REAL(), nullable=True),
        sa.Column("tilt_angle_deg", sa.Double(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storage_locations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("montage_set_name", sa.String(), nullable=True),
        sa.Column("sub_region", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("replaces_acquisition_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind = 'lens_correction' OR (roi_id IS NOT NULL AND specimen_id IS NOT NULL)",
            name=op.f("ck_acquisitions_lineage_required_for_montage"),
        ),
        sa.CheckConstraint("kind IN ('montage', 'lens_correction')", name=op.f("ck_acquisitions_kind_vocab")),
        sa.CheckConstraint(
            "qc_state IN ('pending', 'qc_pass', 'qc_fail', 'needs_review')", name=op.f("ck_acquisitions_qc_state_vocab")
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('complete', 'aborted', 'failed')", name=op.f("ck_acquisitions_status_vocab")
        ),
        sa.CheckConstraint(
            "transfer_state IN ('not_started', 'in_progress', 'complete', 'error')",
            name=op.f("ck_acquisitions_transfer_state_vocab"),
        ),
        sa.CheckConstraint(
            "(status IS NULL) = (end_time IS NULL)", name=op.f("ck_acquisitions_status_terminal_consistency")
        ),
        sa.ForeignKeyConstraint(
            ["acquisition_task_id"],
            ["acquisition_tasks.task_id"],
            name=op.f("fk_acquisitions_acquisition_task_id_acquisition_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.dataset_id"], name=op.f("fk_acquisitions_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["lc_id"], ["lens_corrections.lc_id"], name=op.f("fk_acquisitions_lc_id_lens_corrections")
        ),
        sa.ForeignKeyConstraint(
            ["microscope_id"], ["microscopes.microscope_id"], name=op.f("fk_acquisitions_microscope_id_microscopes")
        ),
        sa.ForeignKeyConstraint(
            ["replaces_acquisition_id"],
            ["acquisitions.acquisition_id"],
            name=op.f("fk_acquisitions_replaces_acquisition_id_acquisitions"),
        ),
        sa.ForeignKeyConstraint(["roi_id"], ["rois.roi_id"], name=op.f("fk_acquisitions_roi_id_rois")),
        sa.ForeignKeyConstraint(
            ["specimen_id"], ["specimens.specimen_id"], name=op.f("fk_acquisitions_specimen_id_specimens")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisitions")),
        sa.UniqueConstraint("acquisition_id", name=op.f("uq_acquisitions_acquisition_id")),
        sa.UniqueConstraint("run_id", name=op.f("uq_acquisitions_run_id")),
    )
    op.create_index(op.f("ix_acquisitions_acquisition_task_id"), "acquisitions", ["acquisition_task_id"], unique=False)
    op.create_index(
        "ix_acquisitions_dataset_id_nn",
        "acquisitions",
        ["dataset_id"],
        unique=False,
        postgresql_where=sa.text("dataset_id IS NOT NULL"),
    )
    op.create_index("ix_acquisitions_dataset_kind_qc", "acquisitions", ["dataset_id", "kind", "qc_state"], unique=False)
    op.create_index(
        "ix_acquisitions_lc_id_nn",
        "acquisitions",
        ["lc_id"],
        unique=False,
        postgresql_where=sa.text("lc_id IS NOT NULL"),
    )
    op.create_index(
        "ix_acquisitions_montage_set_name_nn",
        "acquisitions",
        ["montage_set_name"],
        unique=False,
        postgresql_where=sa.text("montage_set_name IS NOT NULL"),
    )
    op.create_index(
        "ix_acquisitions_replaces_nn",
        "acquisitions",
        ["replaces_acquisition_id"],
        unique=False,
        postgresql_where=sa.text("replaces_acquisition_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_acquisitions_roi_id"), "acquisitions", ["roi_id"], unique=False)
    op.create_index(op.f("ix_acquisitions_specimen_id"), "acquisitions", ["specimen_id"], unique=False)
    op.create_index(op.f("ix_acquisitions_start_time"), "acquisitions", ["start_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_acquisitions_start_time"), table_name="acquisitions")
    op.drop_index(op.f("ix_acquisitions_specimen_id"), table_name="acquisitions")
    op.drop_index(op.f("ix_acquisitions_roi_id"), table_name="acquisitions")
    op.drop_index(
        "ix_acquisitions_replaces_nn",
        table_name="acquisitions",
        postgresql_where=sa.text("replaces_acquisition_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_acquisitions_montage_set_name_nn",
        table_name="acquisitions",
        postgresql_where=sa.text("montage_set_name IS NOT NULL"),
    )
    op.drop_index("ix_acquisitions_lc_id_nn", table_name="acquisitions", postgresql_where=sa.text("lc_id IS NOT NULL"))
    op.drop_index("ix_acquisitions_dataset_kind_qc", table_name="acquisitions")
    op.drop_index(
        "ix_acquisitions_dataset_id_nn", table_name="acquisitions", postgresql_where=sa.text("dataset_id IS NOT NULL")
    )
    op.drop_index(op.f("ix_acquisitions_acquisition_task_id"), table_name="acquisitions")
    op.drop_table("acquisitions")
    op.drop_index(
        "ix_acquisition_tasks_task_group_nn",
        table_name="acquisition_tasks",
        postgresql_where=sa.text("task_group_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_acquisition_tasks_superseded_nn",
        table_name="acquisition_tasks",
        postgresql_where=sa.text("superseded_by IS NOT NULL"),
    )
    op.drop_index("ix_acquisition_tasks_specimen_block", table_name="acquisition_tasks")
    op.drop_index(op.f("ix_acquisition_tasks_roi_id"), table_name="acquisition_tasks")
    op.drop_index(
        "ix_acquisition_tasks_dataset_id_nn",
        table_name="acquisition_tasks",
        postgresql_where=sa.text("dataset_id IS NOT NULL"),
    )
    op.drop_table("acquisition_tasks")
    op.drop_index(op.f("ix_rois_substrate_media_id"), table_name="rois")
    op.drop_index("ix_rois_specimen_block", table_name="rois")
    op.drop_index(op.f("ix_rois_section_id"), table_name="rois")
    op.drop_index("ix_rois_parent_roi_id_nn", table_name="rois", postgresql_where=sa.text("parent_roi_id IS NOT NULL"))
    op.drop_index("ix_rois_dataset_id_nn", table_name="rois", postgresql_where=sa.text("dataset_id IS NOT NULL"))
    op.drop_table("rois")
    op.drop_index("ix_sections_specimen_block", table_name="sections")
    op.drop_index(op.f("ix_sections_section_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_media_id"), table_name="sections")
    op.drop_index("ix_sections_barcode_nn", table_name="sections", postgresql_where=sa.text("barcode IS NOT NULL"))
    op.drop_table("sections")
    op.drop_index(op.f("ix_tiles_tile_id"), table_name="tiles")
    op.drop_index("ix_tiles_supertile_id_nn", table_name="tiles", postgresql_where=sa.text("supertile_id IS NOT NULL"))
    op.drop_index("ix_tiles_focus_score_nn", table_name="tiles", postgresql_where=sa.text("focus_score IS NOT NULL"))
    op.drop_table("tiles")
    op.drop_index("ix_cutting_sessions_specimen_block", table_name="cutting_sessions")
    op.drop_index(op.f("ix_cutting_sessions_operator"), table_name="cutting_sessions")
    op.drop_index(op.f("ix_cutting_sessions_cutting_session_id"), table_name="cutting_sessions")
    op.drop_table("cutting_sessions")
    op.drop_index("ix_lens_corrections_microscope_mag", table_name="lens_corrections")
    op.drop_table("lens_corrections")
    op.drop_index(op.f("ix_datasets_name"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_table("blocks")
    op.drop_index("ix_substrates_media_type_status", table_name="substrates")
    op.drop_index(op.f("ix_substrates_media_id"), table_name="substrates")
    op.drop_table("substrates")
    op.drop_index(op.f("ix_specimens_specimen_id"), table_name="specimens")
    op.drop_table("specimens")
    op.drop_table("microscopes")
    # ### end Alembic commands ###
